//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoEmFoco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpCol
    {
        public int Id { get; set; }
        public string RazaoSocial { get; set; }
        public string CNPJ { get; set; }
        public string Endereco { get; set; }
        public string InscricaoEstadual { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Responsavel { get; set; }
        public Nullable<int> QtdUsuarios { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public bool Ativo { get; set; }
        public string Tipo { get; set; }
    }
}
